const themeList = [
   {
      gradient: 'linear-gradient(45deg, #db03e4, #35afff)',
      primaryColor: '#db03e4',
      primaryText: '#fff',
      secondaryColor: '#35afff',
      secondaryText: '#333',
      title: 'Default',
   },
   {
      gradient: 'linear-gradient(45deg, #ee9ca7, #ffdde1)',
      primaryColor: '#ee9ca7',
      primaryText: '#333',
      secondaryColor: '#ffdde1',
      secondaryText: '#fff',
      title: 'Piggy Pink',
   },
   {
      gradient: 'linear-gradient(45deg, #c6ffdd, #fbd786, #f7797d)',
      primaryColor: '#c6ffdd',
      primaryText: '#333',
      secondaryColor: '#f7797d',
      secondaryText: '#fff',
      title: 'MegaTron',
   },
   {
      gradient: 'linear-gradient(45deg, #12c2e9, #c471ed, #f64f59)',
      primaryColor: '#12c2e9',
      primaryText: '#fff',
      secondaryColor: '#f64f59',
      secondaryText: '#333',
      title: 'JShine',
   },
   {
      gradient: 'linear-gradient(45deg, #b92b27, #1565c0)',
      primaryColor: '#b92b27',
      primaryText: '#fff',
      secondaryColor: '#1565c0',
      secondaryText: '#333',
      title: 'Evening Sunshine',
   },
   {
      gradient: 'linear-gradient(45deg, #aa4b6b, #6b6b83, #3b8d99)',
      primaryColor: '#aa4b6b',
      primaryText: '#fff',
      secondaryColor: '#3b8d99',
      secondaryText: '#333',
      title: 'Memariani',
   },
   {
      gradient: 'linear-gradient(45deg, #c31432, #240b36)',
      primaryColor: '#c31432',
      primaryText: '#fff',
      secondaryColor: '#240b36',
      secondaryText: '#333',
      title: 'Witching Hour',
   },
   {
      gradient: 'linear-gradient(45deg, #f12711, #f5af19)',
      primaryColor: '#f12711',
      primaryText: '#fff',
      secondaryColor: '#f5af19',
      secondaryText: '#333',
      title: 'Flare',
   },
   {
      gradient: 'linear-gradient(45deg, #659999, #f4791f)',
      primaryColor: '#659999',
      primaryText: '#fff',
      secondaryColor: '#f4791f',
      secondaryText: '#333',
      title: 'Metapolis',
   },
   {
      gradient: 'linear-gradient(45deg, #dd3e54, #6be585)',
      primaryColor: '#dd3e54',
      primaryText: '#fff',
      secondaryColor: '#6be585',
      secondaryText: '#333',
      title: 'Kyoo Pal',
   },
   {
      gradient: 'linear-gradient(45deg, #654ea3, #eaafc8)',
      primaryColor: '#654ea3',
      primaryText: '#fff',
      secondaryColor: '#eaafc8',
      secondaryText: '#333',
      title: 'Ultra Voilet',
   },
   {
      gradient: 'linear-gradient(45deg, #e48003, #35cbff)',
      primaryColor: '#e48003',
      primaryText: '#fff',
      secondaryColor: '#35cbff',
      secondaryText: '#333',
      title: 'Burning Orange',
   },
   {
      gradient: 'linear-gradient(45deg, #8a2387, #e94057, #f27121)',
      primaryColor: '#8a2387',
      primaryText: '#fff',
      secondaryColor: '#f27121',
      secondaryText: '#333',
      title: 'Wiretap',
   },
   {
      gradient: 'linear-gradient(45deg, #1e9600, #fff200, #ff0000)',
      primaryColor: '#1e9600',
      primaryText: '#fff',
      secondaryColor: '#ff0000',
      secondaryText: '#333',
      title: 'Rastafari',
   },
   {
      gradient: 'linear-gradient(45deg, #ed213a, #93291e)',
      primaryColor: '#ed213a',
      primaryText: '#fff',
      secondaryColor: '#93291e',
      secondaryText: '#333',
      title: 'Sin City Red',
   },
   {
      gradient: 'linear-gradient(45deg, #fdc830, #f37335)',
      primaryColor: '#fdc830',
      primaryText: '#fff',
      secondaryColor: '#f37335',
      secondaryText: '#333',
      title: 'Citrus Peel',
   },
   {
      gradient: 'linear-gradient(45deg, #da4453, #89216b)',
      primaryColor: '#da4453',
      primaryText: '#fff',
      secondaryColor: '#89216b',
      secondaryText: '#333',
      title: 'Vanusa',
   },
   {
      gradient: 'linear-gradient(45deg, #333333, #dd1818)',
      primaryColor: '#333333',
      primaryText: '#fff',
      secondaryColor: '#dd1818',
      secondaryText: '#333',
      title: 'Pure Lust',
   },
   {
      gradient: 'linear-gradient(45deg, #355c7d, #6c5b7b, #c06c84)',
      primaryColor: '#355c7d',
      primaryText: '#fff',
      secondaryColor: '#c06c84',
      secondaryText: '#333',
      title: 'Red Sunset',
   },
   {
      gradient: 'linear-gradient(45deg, #bc4e9c, #f80759)',
      primaryColor: '#bc4e9c',
      primaryText: '#fff',
      secondaryColor: '#f80759',
      secondaryText: '#333',
      title: 'Shifter',
   },
   {
      gradient: 'linear-gradient(45deg, #108dc7, #ef8e38)',
      primaryColor: '#108dc7',
      primaryText: '#fff',
      secondaryColor: '#ef8e38',
      secondaryText: '#333',
      title: 'Pun Yeta',
   },
   {
      gradient: 'linear-gradient(45deg, #23074d, #cc5333)',
      primaryColor: '#23074d',
      primaryText: '#fff',
      secondaryColor: '#cc5333',
      secondaryText: '#333',
      title: 'Taran tado',
   },
   {
      gradient: 'linear-gradient(45deg, #fc4a1a, #f7b733)',
      primaryColor: '#fc4a1a',
      primaryText: '#fff',
      secondaryColor: '#f7b733',
      secondaryText: '#333',
      title: 'Orange Fun',
   },
   {
      gradient: 'linear-gradient(45deg, #642b73, #c6426e)',
      primaryColor: '#642b73',
      primaryText: '#fff',
      secondaryColor: '#c6426e',
      secondaryText: '#333',
      title: 'Crimson Tide',
   },
]

export default themeList
