const types = {
   LOGIN: 'lOGIN',
   LOGIN_REQUEST: 'LOGIN_REQUEST',
   GET_USER: 'GET_USER',
   CREATE_NEW_USER: 'CREATE_NEW_USER',

   SHOW_BACKDROP: 'SHOW_BACKDROP',
   HIDE_BACKDROP: 'HIDE_BACKDROP',
}

export default types
