const types = {
   LOGIN: 'lOGIN',
   LOGIN_REQUEST: 'LOGIN_REQUEST',

   LOG_OUT: 'LOG_OUT',

   GET_USER_REQUEST: 'GET_USER_REQUEST',
   GET_USER: 'GET_USER',

   CREATE_NEW_USER: 'CREATE_NEW_USER',

   CHANGE_THEME_REQUEST: 'CHANGE_THEME_REQUEST',
   CHANGE_THEME: 'CHANGE_THEME',
   SET_THEME: 'SET_THEME',
   CHANGE_AVATAR: 'CHANGE_AVATAR',
   CHANGE_BACKGROUND: 'CHANGE_BACKGROUND',

   SET_TODOLIST: 'SET_TODOLIST',
   ADD_NEW_TASK: 'ADD_NEW_TASK',
   DELETE_TASK: 'DELET_TASK',
   EDIT_TASK: 'EDIT_TASK',
   SET_READY_TASK: 'SET_READY_TASK',
   SET_COMPLETED_TASK: 'SET_COMPLETED_TASK',

   SET_CONVERSATIONS: 'SET_CONVERSATIONS',
   SET_CUR_CONVERSATION: 'SET_CUR_CONVERSATION',

   GET_NOTIFICATIONS: 'GET_NOTIFICATIONS',
   SEEN_NOTIFICATIONS: 'SEEN_NOTIFICATIONS',
   REMOVE_NOTIFY: 'REMOVE_NOTIFY',

   GET_DIARIES: 'GET_DIARIES',
   ADD_DIARY: 'ADD_DIARY',
   EDIT_DIARY: 'EDIT_DIARY',
   DELETE_DIARY: 'DELETE_DIARY',

   SET_FRIENDS: 'SET_FRIENDS',
   UN_FRIEND: 'UN_FRIEND',

   ADD_ACCOUNT: 'ADD_ACCOUNT',
   REMOVE_ACCOUNT: 'REMOVE_ACCOUNT',

   SET_BLOGS: 'SET_BLOGS',
   ADD_BLOG: 'ADD_BLOG',
   DELETE_BLOG: 'DELETE_BLOG',

   SET_IMAGES: 'SET_IMAGES',
   ADD_IMAGE: 'ADD_IMAGE',
   DELETE_IMAGE: 'DELETE_IMAGE',

   SET_VIDEOS: 'SET_VIDEO',
   ADD_VIDEO: 'ADD_VIDEO',
   DELETE_VIDEO: 'DELETE_VIDEO',

   SET_SHORTS: 'SET_SHORTS',
   ADD_SHORT: 'ADD_SHORT',
   DELETE_SHORT: 'DELETE_SHORT',

   ADD_NEW_SONG: 'ADD_NEW_SONG',
   SET_MY_SONG_LIST: 'SET_MY_SONG_LIST',
   ADD_NEW_PLAYLIST: 'ADD_NEW_PLAYLIST',
   SET_MY_PLAYLIST_LIST: 'SET_MY_PLAYLIST_LIST',
   SET_PLAYING_SONG: 'SET_PLAYING_SONG',
   SET_RECENTLY_LIST: 'SET_RECENTLY_LIST',
   SET_PLAYING_PLAYLIST: 'SET_PLAYING_PLAYLIST',
   SET_RANDOM_SONG_LIST: 'SET_RANDOM_SONG_LIST',
   SET_CUR_PLAYLIST_ID: 'SET_CUR_PLAYLIST_ID',
   SET_PLAYING_AT: 'SET_PLAYING_AT',
   DELETE_SONG: 'DELETE_SONG',
   DELETE_PLAYLIST: 'DELETE_PLAYLIST',

   SHOW_BACKDROP: 'SHOW_BACKDROP',
   HIDE_BACKDROP: 'HIDE_BACKDROP',
}

export default types
