const types = {
   LOGIN: 'lOGIN',
   LOGIN_REQUEST: 'LOGIN_REQUEST',
   GET_USER: 'GET_USER',
   CREATE_NEW_USER: 'CREATE_NEW_USER',

   CHANGE_THEME_REQUEST: 'CHANGE_THEME_REQUEST',
   CHANGE_THEME: 'CHANGE_THEME',

   GET_ALL_TASK_REQUEST: 'GET_ALL_TASK_REQUEST',
   GET_ALL_TASK: 'GET_ALL_TASK',
   ADD_NEW_TASK_REQUEST: 'ADD_NEW_TASK_REQUEST',
   UPDATE_TODOLIST: 'UPDATE_TODOLIST',
   DELETE_TASK_REQUEST: 'DELETE_TASK_REQUEST',
   DELETE_TASK: 'DELET_TASK',
   EDIT_TASK_REQUEST: 'EDIT_TASK_REQUEST',
   EDIT_TASK: 'EDIT_TASK',

   SHOW_BACKDROP: 'SHOW_BACKDROP',
   HIDE_BACKDROP: 'HIDE_BACKDROP',
}

export default types
